# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20171202_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='myblog.Tag'),
        ),
    ]
